const config = {
    AWS: {
        AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY ,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY ,
        AWS_S3_REGION: process.env.AWS_S3_REGION ,
        AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME 
    },
    OUTLOOK_CLIENT: {
        OUTLOOK_CLIENT_ID: process.env.OUTLOOK_CLIENT_ID ,
        OUTLOOK_CLIENT_SECRET: process.env.OUTLOOK_CLIENT_SECRET ,
    },
    GMAIL_CLIENT: {
        GMAIL_CLIENT_ID: process.env.GMAIL_CLIENT_ID ,
        GMAIL_CLIENT_SECRET: process.env.GMAIL_CLIENT_SECRET   
    },
    YAHOO_CLIENT: {
        YAHOO_CLIENT_ID: process.env.YAHOO_CLIENT_ID ,
        YAHOO_CLIENT_CECRET: process.env.YAHOO_CLIENT_CECRET ,  
    },
    JWT_SECRET: process.env.JWT_SECRET ,
    SENDGRID: {
        SENDGRID_KEY: process.env.SENDGRID_KEY ,
        SENDGRID_APPOITMENT_TEMPLATE: process.env.SENDGRID_APPOITMENT_TEMPLATE ,
        SENDGRID_NOTICATION_TEMPLATE: process.env.SENDGRID_NOTICATION_TEMPLATE ,
        SENDGRID_DAILY_REPORT_TEMPLATE: process.env.SENDGRID_DAILY_REPORT_TEMPLATE ,
        SENDGRID_WEEKLY_REPORT_TEMPLATE: process.env.SENDGRID_WEEKLY_REPORT_TEMPLATE ,
        SENDGRID_FOLLOWUP_REMINDER_TEMPLATE: process.env.SENDGRID_FOLLOWUP_REMINDER_TEMPLATE ,
        SENDGRID_APPOINTMENT_REMINDER_TEMPLATE: process.env.SENDGRID_APPOINTMENT_REMINDER_TEMPLATE ,
        SENDGRID_APPOINTMENT_NOTIFICATION_TEMPLATE: process.env.SENDGRID_APPOINTMENT_NOTIFICATION_TEMPLATE ,
        SENDGRID_WELCOME_TEMPLATE: process.env.SENDGRID_WELCOME_TEMPLATE ,
        SENDGRID_SIGNUP_FLOW_FIRST: process.env.SENDGRID_SIGNUP_FLOW_FIRST ,
        SENDGRID_SIGNUP_FLOW_SECOND: process.env.SENDGRID_SIGNUP_FLOW_SECOND ,
        SENDGRID_SIGNUP_FLOW_REACH: process.env.SENDGRID_SIGNUP_FLOW_REACH ,
        SENDGRID_SIGNUP_FLOW_THIRD: process.env.SENDGRID_SIGNUP_FLOW_THIRD ,
        SENDGRID_SIGNUP_FLOW_FORTH: process.env.SENDGRID_SIGNUP_FLOW_FORTH ,
        SENDGRID_SYSTEM_NOTIFICATION: process.env.SENDGRID_SYSTEM_NOTIFICATION 
    },
    TWILIO: {
        TWILIO_SID: process.env.TWILIO_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN ,
        TWILIO_NUMBER: process.env.TWILIO_NUMBER 
    },
    VAPID: {
        PUBLIC_VAPID_KEY: process.env.PUBLIC_VAPID_KEY ,
        PRIVATE_VAPID_KEY: process.env.PRIVATE_VAPID_KEY 
    },
    STRIPE: {
        SECRET_KEY: process.env.SECRET_KEY ,
        BILLING_CYCLE: process.env.BILLING_CYCLE ,
        PRODUCT_ID: process.env.PRODUCT_ID ,
        PRIMARY_PLAN: process.env.PRIMARY_PLAN ,
        PRIOR_PLAN: process.env.PRIOR_PLAN ,
        PRIMARY_PLAN_AMOUNT: process.env.PRIMARY_PLAN_AMOUNT ,
        PRIOR_PLAN_AMOUNT: process.env.PRIOR_PLAN_AMOUNT ,
        LIMIT: process.env.LIMIT 
    },
    MAX_CONTACT: process.env.MAX_CONTACT ,
    DEFAULT_PASS: process.env.DEFAULT_PASS 
}

module.exports = config;
